
DELIMITER //

CREATE PROCEDURE sp_CHECK_CART_EXISTS(IN CURRENTUSER INT)
BEGIN
	SELECT * FROM cart WHERE userId = CURRENTUSER;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE sp_CREATE_CART(IN CURRENTUSER INT, IN CURRENTADDRESS VARCHAR(500))
BEGIN
    DECLARE CART_ID INT DEFAULT 0;
    SELECT id INTO CART_ID FROM cart WHERE userId = CURRENTUSER;
    IF CART_ID = 0 THEN
        INSERT INTO cart(userId, deliveryAddress) VALUES(CURRENTUSER, CURRENTADDRESS);
        SELECT LAST_INSERT_ID() INTO CART_ID;
    END IF;
    SELECT CART_ID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE sp_ADD_NEW_ITEM(IN CART_ID INT, IN ITEM_ID INT, IN ITEM_COUNT INT)
BEGIN
	DECLARE ITEM_PRICE FLOAT DEFAULT 0.0;
    DECLARE EXISTING_NUM INT DEFAULT 0;
    SELECT COUNT(*) INTO EXISTING_NUM FROM cart_items WHERE itemId = ITEM_ID;
    IF EXISTING_NUM = 0 THEN
        INSERT INTO cart_items (cartId, itemId, itemCount) VALUES (CART_ID, ITEM_ID, ITEM_COUNT);
    END IF;
    SELECT id as Id, itemId as ItemId, itemCount as ItemCount, itemPrice as ItemPrice FROM cart_items WHERE cartId = CART_ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_REMOVE_CART_ITEM(IN CART_ID INT, IN ITEM_ID INT)
BEGIN
    DELETE FROM cart_items WHERE cartId = CART_ID AND itemId = ITEM_ID;
    SELECT ROW_COUNT() AS UPDATED;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_READ_CART(IN USER_ID INT)
BEGIN
    SELECT 
        CRT.id,
        ORD.orderType, 
        CRT.deliveryAddress,
        CRT.coupon,
        CRT.hasCoupon,
        CRT.shipCost,
        CRT.cartTotal,
        CRT.instructions
    FROM cart CRT
    JOIN order_type ORD ON ORD.id = CRT.orderType
    WHERE userId = USER_ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_READ_CART_COMMENTS(IN CART_ID INT)
BEGIN
SELECT
    CRT.id,
    CRT.cartId,
    CRT.userId,
    CRT.comment
FROM cart_comment CRT
WHERE cartId = CART_ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_GET_CART_ITEMS(IN CART_ID INT)
BEGIN
    SELECT
        ITM.id,
        ITM.itemId,
        ITM.itemCount,
        ITM.itemPrice
    FROM cart_items ITM
    WHERE ITM.cartId = CART_ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE sp_UPDATE_CART_ITEM(IN ITEM_ID INT, IN ITEM_COUNT INT)
BEGIN
    UPDATE cart_items 
    SET
        itemCount = ITEM_COUNT
    WHERE
        itemId = ITEM_ID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE sp_REMOVE_CART (IN CART_ID INT)
BEGIN
    DELETE FROM cart_items WHERE cartId = CART_ID;
    DELETE FROM cart WHERE id = CART_ID;
END //
DELIMITER ;